name: Release

on:
  release:
    types: [published]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    name: GPR
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://npm.pkg.github.com/
        scope: '@jonhue'
    - name: Install Tree-sitter
      run: yarn global add tree-sitter-cli
    - name: Generate parser
      run: yarn generate
    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GPR_AUTH_TOKEN }}

  publish-npm:
    runs-on: ubuntu-latest
    name: NPM
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - name: Install Tree-sitter
      run: yarn global add tree-sitter-cli
    - name: Generate parser
      run: yarn generate
    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
